### ISSUE TITLE
Handle folders with ! in name

### ISSUE THREAD

**Issue by Phanx** [Phanx/packager#4]
eg. `!ClassColors`, currently gets single quotes in the ZIP file name and top-level folder. Incomplete fix:

```
    _cdt_destdir="${2//\'/}" # HERE

    echo "Copying files from \`\`${_cdt_srcdir#$topdir/}'' into \`\`${_cdt_destdir#$topdir/}'':"
```

```
### Create the final zipfile for the addon.
###

if [ -z "$skip_zipfile" ]; then
    contents=${contents//\']/} # HERE
    package=${package//[\'!]/} #HERE
```

**Comment by nebularg** [comment]
Have you tried removing the single quotes from the .pkgmeta package-as line?

**Comment by Phanx** [comment]
No, I'd actually totally forgotten they were in the .pkgmeta; I was working under the assumption the quotes were related to bash's history expansion "feature". The fact that they're literal quotes in the .pkgmeta line means this should be much easier to solve (just strip them out when reading the .pkgmeta). However, I think the solution should happen in the script, as having the quotes in the .pkgmeta line is required for the Curse packager when there's an exclamation point. Thanks for the tip.
